### ISSUE TITLE
Use better fallback font

### ISSUE THREAD

**Issue by RoelN** [Wakamai-Fondue/wakamai-fondue-site#103]
Unsupported chars are now shown in `monospace`. This can be confusing, e.g. if you drop in fonts for other scripts, or emoji fonts. Perhaps use https://github.com/adobe-fonts/adobe-notdef

**Comment by ohbendy** [comment]
Ah, interesting you are looking at it the other way from how I was! When I drop a variable font which doesn't contain Latin letters, I'd like to be able to see the letters that _are_ in the font, in the little instance preview boxes, rather than trying to substitute a different font that contains the characters that are not in the font I dropped. My suggestion would be to have those boxes just pick the first two letters of the script it does contain.

**Comment by RoelN** [comment]
Ideally, Wakamai Fondue should do that: use the characters that _are_ in the font. But this issue covers more than just those named instance buttons: having had a taste of how complex language/script support is, I want to put a fail-safe in place for when a user manually enters a text, or when WF can't dish up characters in a font. (Or they aren't turned into the proper glyph because some feature fails). In that case I want to make super clear that that character is not supported.

With this safety net in place, next step is showing proper text in the tester, and characters in the named instances buttons :-)

**Comment by ohbendy** [comment]
That sounds like a very good approach. 
 
After I wrote it I realised it's not going to be completely straightforward to change the content of those elements depending on what script(s) the font contains.

**Comment by RoelN** [comment]
I'll close this issue, as Adobe Notdef is now in use. I'll create a separate issue for showing default text depending on the font's script(s).
